function [fitresult, gof] = createFit1(Wavelength, Transmission)
%CREATEFIT1(WAVELENGTH,TRANSMISSION)
%  Create a fit.
%
%  Data for 'TightSplinefit 1' fit:
%      X Input : Wavelength
%      Y Output: Transmission
%      Weights : Transmission
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Mar-2017 03:20:21


%% Fit: 'TightSplinefit 1'.
[xData, yData, weights] = prepareCurveData( Wavelength, Transmission, Transmission );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
excludedPoints = (xData < 400.01) | (xData > 950.23) | (yData < 0) | (yData > 100);
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.000477368132778731;
opts.Weights = weights;
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




